POST http://localhost:8080/events
content-type: application/json

{

    "Name": "Test event",
    "Description": "Test description for event",
    "Location": "Test location",
    "DateTime": "2024-04-13T08:30:00Z"

}